### ISSUE TITLE
firbase/app

### ISSUE THREAD

**Issue by falaFulani** [javebratt/ionic-angular-event-manager#1]
Hello, 

In the auth.guard.ts the import * as firebase from 'firebase/app';  throws an error since the module is not available in the app. 

To fix the error, i run npm install @angular/fire firebase --save

**Comment by javebratt** [comment]
Hey there, no, don't install `@angular/fire`. We won't use it on this app. The bug was that in the second lesson where I tell people to install Firebase I used the `-g`, like `npm install -g firebase` and it should be without the `-g`: `npm install firebase`
